language: java

before_install:
  # Install base Android SDK
  # see http://d.hatena.ne.jp/gfx/20131230/1388377416
  - sudo apt-get update -qq
  - sudo apt-get install -qq libstdc++6:i386 lib32z1
  - export COMPONENTS=build-tools-19.1.0,android-18,extra
  - curl -L https://raw.github.com/embarkmobile/android-sdk-installer/master/android-sdk-installer | bash /dev/stdin --install=$COMPONENTS
  - source ~/.android-sdk-installer/env
  - export TERM=dumb # to get clean gradle output

script: ./gradlew clean test

jdk:
  - openjdk7
  - oraclejdk7

#before_script:
#  # Create and start emulator
#  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
#  - emulator -avd test -no-skin -no-audio -no-window &
#  - adb wait-for-device
#  - adb shell input keyevent 82 &
#
# script: ./gradlew clean test